### ISSUE TITLE
[FEATURE REQUEST] power-profiles-daemon removed on Fedora 41

### ISSUE THREAD

**Issue by Bammede** [dmy3k/auto-power-profile#10]
Just wanted to tell you, Fedora 41 will abond power-profiles-daemon in favor to TuneD.

**Comment by dmy3k** [comment]
Thanks for the update. The extension should still work, as fedora will include `tuned-ppd` package for compatibility: https://www.phoronix.com/news/Fedora-41-Goes-Tuned-PPD

Will need to verify closer to release date of F41

**Comment by dmy3k** [comment]
FYI
Checked on Fedora 41 beta. Extension works as expected
