### ISSUE TITLE
[FEATURE REQUEST] Time based switching?

### ISSUE THREAD

**Issue by francoism90** [dmy3k/auto-power-profile#4]
**Is your feature request related to a problem? Please describe.**
Thanks for your extension! Would it be possible to implement a timer function?

I'm running a system, that runs 24/7, but it always needs to be available.

**Describe the solution you'd like**
- `1:00am till 6.30am` - `power-saver` profile
- `6.30am till 1:00am` - `balanced` profile (or as fallback to the default profile)

**Describe alternatives you've considered**
Using `powerprofilesctl set balanced/power-saver` based on systemd timers.  

**Additional context**
Gnome Shell 45
Fedora Silverblue 40

**Comment by dmy3k** [comment]
It is possible to implement such feature. Let's have it more detailed first.

- What priority should scheduled mode have ? It could be highest, than it would inhibit mode change on AC connect/disconnect and battery saver on low battery threshold
- To make such behavior clear to end user, extension probably needs to sent notifications when scheduled mode is active.

**Comment by francoism90** [comment]
It's indeed a schedule mode, and thanks for your consideration!

Just FYI: Yesterday I've implemented a simple systemd timer, which also does the trick. So only implement this when you want and think is useful for others as well. :)

I don't know how much work and how difficult the APIs are; but I agree with both your solutions. It would be great if the user could set the mode/priority, but I don't know the impact/time for this.

On my Apple from Work, the chooses for Low Power Mode are:
- Always
- Only on Batter
- Only on Power Adapter

So Always would overrule the scheduler, I think.

**Comment by dmy3k** [comment]
After some investigation I came to conclusion that time-based switching is somewhat out-of scope here. The feature can be a whole separate extension.

I would like to keep current extension as simple as possible, e.g as per other platforms

- [KDE](https://conf.kde.org/event/1/contributions/16/attachments/14/15/davidredondo-ppip.pdf)
- [Win11](https://www.windowscentral.com/how-change-power-modes-performance-or-battery-windows-11)
- [macos](https://support.apple.com/en-us/HT212852)

However, feel free to share your script, it might be useful for other folks. Thanks!

**Comment by francoism90** [comment]
@dmy3k No worries!

I'm using something like this:
```bash
$ cat ~/.config/systemd/user/power-profile@.service                                    
[Unit]
Description=Set Power Profile to profile

[Service]
ExecStart=/usr/bin/powerprofilesctl set %i

[Install]
WantedBy=default.target
```
```bash
$ cat ~/.config/systemd/user/power-profile@power-saver.timer
[Unit]
Description=Run power-saver daily

[Timer]
OnCalendar=*-*-* 0:30:00

[Install]
WantedBy=timers.target
```
